dist: precise
language: cpp
compiler:
  - clang

# whitelisted packages can be obtained quickly without downloading
# doxygen is out of date, tho so we download its binaries
addons:
  mariadb: '10.0'
  apt:
    packages:
      - cmake
      - build-essential
      - cppcheck
      - git
      - make
      - binutils-dev
      - openssl
      - libssl-dev
      - zlib1g-dev
      - zip
      - unzip
      - php5-cli
      - php5-mysql

git:
  depth: 1

before_install:
  - sudo apt-get -qq install mariadb-client libace-dev
  - if [[ $TRAVIS_PULL_REQUEST == 'true' ]]; then exit; fi
  - curl -o doxygen.tar.gz https://oregon-core.net/travis/doxygen.tar.gz
  - tar xzf doxygen.tar.gz
  - sudo install -m 755 doxygen /usr/bin
  - sudo install -m 755 doxyindexer /usr/bin

install:
  - mkdir build
  - cd build
  - cmake .. -DSERVERS=1 -DTOOLS=0 -DSCRIPTS=1 -DWITH_DOCS=1 -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0
# we have 1.5 cpu so 2 jobs at a time are sufficient
  - make -j 4 -k && make install
