dist: precise
language: cpp
compiler:
  - clang

# whitelisted packages can be obtained quickly without downloading
# doxygen is out of date, tho so we download its binaries
addons:
  apt:
    packages:
      - cmake
      - build-essential
      - cppcheck
      - git
      - make
      - binutils-dev
      - openssl
      - libssl-dev
      - zlib1g-dev
      - zip
      - unzip
      - php5-cli
      - php5-mysql

git:
  depth: 1

before_install:
  - sudo apt-get -qq install libace-dev

install:
  - mkdir build
  - cd build
  - cmake ../ -DSERVERS=1 -DTOOLS=0 -DSCRIPTS=1 -DWITH_DOCS=1 -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0
# we have 1.5 cpu so 2 jobs at a time are sufficient
  - make -j8
